// <auto-generated />
using System;
using Hypercode.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Hypercode.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241007121638_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Hypercode.Domain.Entities.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FinishedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ProjectCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("URL")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectCategoryId");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Amet dolorem voluptate beatae ratione quo error. Accusantium rerum impedit, obcaecati nam aliquam culpa nemo quidem voluptates, optio quam sint beatae architecto!",
                            FinishedDate = new DateTime(2022, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Datakadeh",
                            ProjectCategoryId = 1,
                            URL = "https://datakadeh.com/"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Amet dolorem voluptate beatae ratione quo error. Accusantium rerum impedit, obcaecati nam aliquam culpa nemo quidem voluptates, optio quam sint beatae architecto!",
                            FinishedDate = new DateTime(2023, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Davazdah",
                            ProjectCategoryId = 1,
                            URL = "https://12application.ir/"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Amet dolorem voluptate beatae ratione quo error. Accusantium rerum impedit, obcaecati nam aliquam culpa nemo quidem voluptates, optio quam sint beatae architecto!",
                            FinishedDate = new DateTime(2021, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Arnika Stone",
                            ProjectCategoryId = 1,
                            URL = "https://arnika-stone.com/"
                        });
                });

            modelBuilder.Entity("Hypercode.Domain.Entities.ProjectCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ProjectCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Websites"
                        });
                });

            modelBuilder.Entity("Hypercode.Domain.Entities.Project", b =>
                {
                    b.HasOne("Hypercode.Domain.Entities.ProjectCategory", null)
                        .WithMany("Projects")
                        .HasForeignKey("ProjectCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Hypercode.Domain.Entities.ProjectCategory", b =>
                {
                    b.Navigation("Projects");
                });
#pragma warning restore 612, 618
        }
    }
}
